filetype off

colo desert
set guifont=Menlo\ Regular\ for\ Powerline:h14
execute pathogen#infect('pathogen/{}')
set nobackup
set noswapfile
"set directory=~/.vim/swap/
set guitablabel=%t

set smartindent
set smarttab
set expandtab
set softtabstop=4
set tabstop=4
set shiftwidth=4
set listchars=tab:>-,trail:-

set history=50
set ruler
set showcmd
set incsearch

set number
set autoindent
set mouse=a
set scrolloff=5
set ignorecase
set smartcase
set hid

set nowrap
set noswapfile
syn on
set confirm

set encoding=utf-8
set fileencodings=utf-8,chinese,latin-1
set fileencoding=utf-8
set fileformat=dos
set fileformats=dos,unix

" vim 自身命令行模式智能补全
set wildmenu

" 基于语法进行代码折叠
" za，打开或关闭当前折叠；zM，关闭所有折叠；zR，打开所有折叠
set foldmethod=syntax
" 启动时关闭折叠代码
set nofoldenable

set laststatus=2
" 高亮当前行
set cursorline
"set cursorcolumn
" 高亮搜索结果
set hlsearch
set backspace=indent,eol,start

language messages zh_CN.utf-8

filetype on
filetype plugin on
filetype plugin indent on

command W w
command Q q
nmap <F2> :tabprevious<CR>
nmap <F3> :tabnext<CR>
nmap <F5> :e<CR>

au BufRead,BufNewFile *.lh set filetype=lua
au BufRead,BufNewFile BUILD set filetype=python
au BufRead,BufNewFIle *.{md,mkd,mkdn,mark*} set filetype=markdown

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
" call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
" Plugin 'VundleVim/Vundle.vim'
" Plugin 'fatih/vim-go'
" Plugin 'moll/vim-node'
" Plugin 'mileszs/ack.vim'
" Plugin 'dyng/ctrlsf.vim'
" Plugin 'SirVer/ultisnips'
" Plugin 'honza/vim-snippets'
" Plugin 'scrooloose/nerdtree'
" Plugin 'Valloric/YouCompleteMe'
" Plugin 'derekwyatt/vim-fswitch'
" Plugin 'jistr/vim-nerdtree-tabs'
" Plugin 'pangloss/vim-javascript'
" Plugin 'scrooloose/nerdcommenter'
" Plugin 'fholgado/minibufexpl.vim'
" Plugin 'hynek/vim-python-pep8-indent'
" Plugin 'jelera/vim-javascript-syntax'
" Plugin 'terryma/vim-multiple-cursors'
" Plugin 'nathanaelkane/vim-indent-guides'
" Plugin 'octol/vim-cpp-enhanced-highlight'

" call vundle#end()            " required
filetype plugin indent on      " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
let mapleader=";"

au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)

au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)

au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)

au FileType go nmap <Leader>gb <Plug>(go-doc-browser)

au FileType go nmap <Leader>s <Plug>(go-implements)
au FileType go nmap <Leader>i <Plug>(go-info)

" 定义快捷键关闭当前分割窗口
nmap <Leader>q :q<CR>

" 随 vim 自启动
let g:indent_guides_enable_on_vim_startup=1
" 从第二层开始可视化显示缩进
let g:indent_guides_start_level=2
" 色块宽度
let g:indent_guides_guide_size=1
" 快捷键 i 开/关缩进可视化
:nmap <silent> <Leader>i <Plug>IndentGuidesToggle

" fswitch
" *.cpp 和 *.h 间切换
au! BufEnter *.cpp let b:fswitchdst = 'hpp,h' | let b:fswitchlocs = './,./include,../include'
nmap <silent> <Leader>of :FSHere<cr>

" YouCompleteMe
nnoremap <leader>jc :YcmCompleter GoToDeclaration<CR>
" 只能是 #include 或已打开的文件
nnoremap <leader>jd :YcmCompleter GoToDefinition<CR>
" YCM 补全菜单配色
" " 菜单
highlight Pmenu ctermfg=2 ctermbg=3 guifg=#005f87 guibg=#EEE8D5
" 选中项
highlight PmenuSel ctermfg=2 ctermbg=3 guifg=#AFD700 guibg=#106900
" 补全功能在注释中同样有效
let g:ycm_complete_in_comments=1
" 允许 vim 加载 .ycm_extra_conf.py 文件，不再提示
let g:ycm_confirm_extra_conf=0
" 开启 YCM 标签补全引擎
let g:ycm_collect_identifiers_from_tags_files=1
" 引入 C++ 标准库tags
"set tags+=/data/misc/software/misc./vim/stdcpp.tags
" YCM 集成 OmniCppComplete 补全引擎，设置其快捷键
" inoremap <leader>; <C-x><C-o>
" 补全内容不以分割子窗口形式出现，只显示补全列表
set completeopt-=preview
" 从第一个键入字符就开始罗列匹配项
let g:ycm_min_num_of_chars_for_completion=1
" 禁止缓存匹配项，每次都重新生成匹配项
let g:ycm_cache_omnifunc=0
" 语法关键字补全
let g:ycm_seed_identifiers_with_syntax=1

" UltiSnips 的 tab 键与 YCM 冲突，重新设定
let g:UltiSnipsExpandTrigger="<leader><tab>"
let g:UltiSnipsJumpForwardTrigger="<leader><tab>"
let g:UltiSnipsJumpBackwardTrigger="<leader><s-tab>"

" 使用 NERDTree 插件查看工程文件。设置快捷键，速记：file list
nmap <Leader>e :NERDTreeToggle<CR>
" 设置NERDTree子窗口宽度
let NERDTreeWinSize=32
" 设置NERDTree子窗口位置
let NERDTreeWinPos="right"
" 显示隐藏文件
let NERDTreeShowHidden=1
" NERDTree 子窗口中不显示冗余帮助信息
let NERDTreeMinimalUI=1
" 删除文件时自动删除文件对应 buffer
let NERDTreeAutoDeleteBuffer=1
let NERDTreeIgnore=['^bazel-']

nnoremap <Leader>i :ib<CR>
nnoremap <Leader>l :ls<CR>
nnoremap <Leader>b :bp<CR>
nnoremap <Leader>f :bn<CR>
nnoremap <Leader>g :e#<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>

" 显示/隐藏 MiniBufExplorer 窗口
"map <Leader>bl :MBEToggle<cr>
" buffer 切换快捷键
"map <C-Tab> :MBEbn<cr>
"map <C-S-Tab> :MBEbp<cr>

" 使用 ctrlsf.vim 插件在工程内全局查找光标所在关键字
nnoremap <Leader>sf :CtrlSF<CR>

set rtp+=/usr/local/lib/python2.7/site-packages/powerline/bindings/vim
set rtp+=/usr/local/lib/python2.7/dist-packages/powerline/bindings/vim

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'


