#!/bin/bash

# bash_profile

# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

# Up-front dotfiles configuration
# Not part of `load_dotfiles` because it must be sourced before anything else
# to be sure that commands like `brew` (when installed in a custom location)
# are already added to the PATH.
[ -r $HOME/.dotfilesrc ] && source $HOME/.dotfilesrc;

# # Location of my Bash files
# BASEDIR="${HOME}/.bash"


# # Define file includes
# BASHINCS=(".bash_aliases" ".bash_exports" ".bash_functions" ".bash_linux" ".bash_options" ".bash_mac")

# # Load the file includes if they exist
# for file in ${BASHINCS[@]}; do
#   [ -f $BASEDIR/$file ] && source $BASEDIR/$file;
# done
# unset file

load_dotfiles() {
    declare -a files=(
        ##$HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
        $HOME/.dotfiles/shell/bash/bash_options # Options
        $HOME/.dotfiles/shell/bash/bash_exports # Exports
        $HOME/.dotfiles/shell/bash/bash_aliases # Aliases
        $HOME/.dotfiles/shell/bash/functions/*  # Functions
        $HOME/.dotfiles/shell/bash/bash_prompt  # Custom bash prompt
        $HOME/.dotfiles/shell/bash/bash_paths   # Path modifications
        # if [ -s /usr/local/bin/brew ]; then
        #   if [ -s $(brew --prefix)/etc/bash_completion ]; then
        #     $(brew --prefix)/etc/bash_completion
        #   fi
        # fi
        [[ "$(uname)" == "Darwin" ]] && $(brew --prefix)/etc/bash_completion # Bash completion (installed via Homebrew)
        $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
    )

    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

load_dotfiles
unset load_dotfiles
