#!/bin/bash

# bash_aliases

# Allow aliases to be with sudo
alias sudo="sudo "

# base64 conversion
alias base64-encode='perl -MMIME::Base64 -e "print encode_base64(<>)" <<<'
alias base64-decode='perl -MMIME::Base64 -e "print decode_base64(<>)" <<<'

alias -g      ...=../..
alias -g     ....=../../..
alias -g    .....=../../../..
alias -g   ......=../../../../..
alias -g  .......=../../../../../..
alias -g ........=../../../../../../..

# Easier navigation: .., ..., ~ and -
alias -- -="cd -"
alias cd..="cd .."
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias cd..='cd ../'                         # Go back 1 directory level (for fast typers)
alias ..='cd ../'                           # Go back 1 directory level
alias ...='cd ../../'                       # Go back 2 directory levels
alias .3='cd ../../../'                     # Go back 3 directory levels
alias .4='cd ../../../../'                  # Go back 4 directory levels
alias .5='cd ../../../../../'               # Go back 5 directory levels
alias .6='cd ../../../../../../'            # Go back 6 directory levels
alias ~="cd ~"                              # ~:            Go Home

alias c='clear'                             # c:            Clear terminal display
alias cl="clear"
alias cls='clear'
alias cdc="cd; clear"

# Shortcuts
alias d="cd ~/Documents/Dropbox"
alias df="df -h"

alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias dir='dir --color=auto'
if which 'gdir' > /dev/null 2>&1; then
    # gls provids by coreutils from macports
  alias dir='gdir --color=auto'
fi
alias dh='df -h'
alias dm='df -m'
alias df='df -h'
alias du='du -c -h'
# alias diff='colordiff'              # requires colordiff package
 [[ -x $(which colordiff) ]] && alias diff=colordiff
alias edit='subl'                           # edit:         Opens any file in sublime editor
alias f='open -a Finder ./'                 # f:            Opens current directory in MacOS Finder

alias cp='cp -iv'                           # Preferred 'cp' implementation
alias mv='mv -iv'                           # Preferred 'mv' implementation
alias rm='rm -iv'
if which trash > /dev/null 2>&1; then
  alias rm="trash"
fi
alias md="mkdir -p"
alias mkdir='mkdir -pv'                     # Preferred 'mkdir' implementation
alias rd="rmdir"

alias less='less -FSRXc'                    # Preferred 'less' implementation
# alias edit='subl'                           # edit:         Opens any file in sublime editor
alias f='open -a Finder ./'                 # f:            Opens current directory in MacOS Finder

alias p="cd ~/work/projects"

alias whence='type -a'                        # where, of a sort

# Cute shell shortcuts
alias pms='sudo pm-suspend'
alias psg='ps -A | grep'
alias smi='sudo make install'
alias cp='cp -iv'                           # Preferred 'cp' implementation
alias mv='mv -iv'                           # Preferred 'mv' implementation
alias rm='rm -iv'
alias mkdir='mkdir -pv'                     # Preferred 'mkdir' implementation

# Enable color support of ls and also add handy aliases
# Enable color support of ls and also add handy aliases
if [[ -x /usr/bin/dircolors ]]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
# Generic command adaptations.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'


# This one is to take care of make
# Give me a nice, distinguishable make output
alias make='clear && make'
alias m='make'

# List dir contents aliases
# ref: http://ss64.com/osx/ls.html
# Long form no user group, color
case `uname` in
    Linux)
        alias ls='ls -hF --color=auto' ;
        alias lsd='ls -dAFh --color=auto .[^.]*'; # ls Dotfiles
        alias lst='ls -hFtl --color=auto | grep $(date +%Y-%m-%d)' #ls Today
    ;;
    Darwin|*BSD)
        # Long form no user group, color
        alias l='ls -oCFG'
        # List all except . and ..., color, mark file types, long form no user group, file size
        alias la='ls -AGFoh'
        alias ls='ls -hFG';
        alias ll='ls -FGlAhp'                       # Preferred 'ls' implementation
        alias lal='ls -alhG'
        # Order by last modified, long form no user group, color
        alias lt="ls -toG"
        # List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
        alias lat="ls -AGFoth"
        alias lsd='ls -dAFhG .[^.]*'; # ls Dotfiles
        alias lst='ls -hFtlG | grep $(date +%Y-%m-%d)'
        # Open file in existing MacVim window
        alias gvim="open -a MacVim"
        alias mvim="open -a MacVim"
    ;;
esac

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

#alias h='fc -li 1000'
alias h='history'
alias help='man'

# alias nano='nano -c'

alias tailf='tail -f'

if which vim &>/dev/null; then
    alias vi='vim'
fi

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"

alias which='type -all'                     # which:        Find executables
alias path='echo -e ${PATH//:/\\n}'         # path:         Echo all executable Paths
alias show_options='shopt'                  # Show_options: display bash options settings
alias fix_stty='stty sane'                  # fix_stty:     Restore terminal settings when screwed up
alias cic='set completion-ignore-case On'   # cic:          Make tab-completion case-insensitive

alias DT='tee ~/Desktop/terminalOut.txt'            # DT:           Pipe content to file on MacOS Desktop
alias qfind="find . -name "                 # qfind:    Quickly search for file
# Cool colors for man pages
alias man="TERMINFO=~/.terminfo TERM=mostlike LESS=C PAGER=less man"

# Git Commands
# Add and Commit are used as functions
alias gpo='git push origin master'
alias gp='git pull'
alias gs='git status'
alias gd='git diff'
alias gr='git reflog'
alias glf='git ls-files'

#   memHogsTop, memHogsPs:  Find memory hogs
#   -----------------------------------------------------
alias memHogsTop='top -l 1 -o rsize | head -20'
alias memHogsPs='ps wwaxm -o pid,stat,vsize,rss,time,command | head -10'

#   cpuHogs:  Find CPU hogs
#   -----------------------------------------------------
alias cpu_hogs='ps wwaxr -o pid,stat,%cpu,time,command | head -10'

#   topForever:  Continual 'top' listing (every 10 seconds)
#   -----------------------------------------------------
alias topForever='top -l 9999999 -s 10 -o cpu'

#   ttop:  Recommended 'top' invocation to minimize resources
#   ------------------------------------------------------------
#       Taken from this macosxhints article
#       http://www.macosxhints.com/article.php?story=20060816123853639
#   ------------------------------------------------------------
alias ttop="top -R -F -s 10 -o rsize"



# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Flush DNS cache
alias flushdns="dscacheutil -flushcache"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias showdeskicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedeskicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
