#!/bin/bash
#!/usr/bin/env bash
##     _             _
#    | |__  __ _ __| |_  _ _ __
#   _| '_ \/ _` (_-< ' \| '_/ _|
#  (_)_.__/\__,_/__/_||_|_| \__|
#
############################################################
# Simple but Cute and Helpful (TM) Bash Settings
# bashrc
# cat feedback >> "xiaojianfang558@gmail.com"
############################################################

# ${HOME}/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples


# If not running interactively, don't do anything
# [ -z "$PS1" ] && return
# if [[ $- != *i* ]] ; then
     # Shell is non-interactive.  Be done now!
#      return
# fi
case $- in
    *i*) ;;
      *) return;;
esac


# SET A CUSTOM PROMPT
#
#  \t - time
#  \d - date
#  \n - newline
#  \s - Shell name
#  \W - The current working directory
#  \w - The full path of the current working directory.
#  \u - The user name
#  \h - Hostname
#  \# - The command number of this command.
#  \! - The history number of the current command
#
# COLORS
#
#   \[\e[90m\]      = grey for brackets []
#   \[\e[01;36m\]   = cyan for \w path and $ prompt
#   \[\e[0m\]       = reset colors
#
# PS1='\[\e[90m\][\[\e[0m\]\[\e[01;36m\]\w\[\e[0m\]\[\e[90m\]]\[\e[0m\]\[\e[01;36m\]\$\[\e[0m\] '

[ -n "$PS1" ] && source ~/.bash_profile
