#!/bin/zsh
# -*- coding:utf-8 -*-
###############################################################################
# This file is load **after** .zshrc
#
# Reminder:
# 1. `~/.zshenv` :         Usually run for every zsh
# 2. `$ZDOTDIR/.zprofile`: Run for login shells
# 3. `$ZDOTDIR/.zshrc`:    Run for interactive shells.`
# 4. `$ZDOTDIR/.zlogin`:   Run for login shells (**after** .zshrc)
# Load RVM into a shell session *as a function*

SSH_ENV=${HOME}/.ssh/environment

function start_agent {
     echo "Initialising new SSH agent..."
     /usr/bin/ssh-agent | sed 's/^echo/#echo/' >! ${SSH_ENV}
     chmod 600 ${SSH_ENV}
     . ${SSH_ENV} > /dev/null
     /usr/bin/ssh-add;
}

# https://github.com/nvbn/thefuck
(( $+commands[thefuck] )) && eval "$(thefuck --alias)"

# Source SSH settings, if applicable

if [[ -f "${SSH_ENV}" ]]; then
     . ${SSH_ENV} > /dev/null
     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent > /dev/null || {
         start_agent;
     }
else
     start_agent;
fi